import { Inter } from "next/font/google";
import Navigation from "../components/Navigation";
import "./globals.css";
import { SocialProvider } from "@/contexts/socialContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <SocialProvider><main>{children}</main></SocialProvider>
      </body>
    </html>
  );
}
